[package]
name = "alexandria_macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bigdecimal = "0.4.7"
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.12.2"
cairo-lang-syntax = "2.12.2"
cairo-lang-filesystem = "2.12.2"
cairo-lang-utils = "2.12.2"
