[package]
name = "alexandria_macros"
version.workspace = true
description = "A set of useful macros"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/macros"
edition = "2024_07"
cairo-version = "2.15.0"

[cairo-plugin]

[tool]
fmt.workspace = true

[dev-dependencies]
cairo_test.workspace = true
