[package]
name = "alexandria_evm"
version.workspace = true
description = "An implementation similar to Solidity bytes written in Cairo 1"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/evm"
edition = "2023_11"
cairo-version = "2.12.2"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version ="0.6.1" }
alexandria_bytes = { path = "../bytes", version ="0.6.1" }

[dev-dependencies]
snforge_std.workspace = true
