[package]
name = "alexandria_math"
version.workspace = true
description = "A set of math libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/math"
edition = "2023_11"
cairo-version = "2.11.2"

[tool]
fmt.workspace = true

[dev-dependencies]
cairo_test.workspace = true
