[package]
name = "alexandria_math"
version = "0.2.0"
description = "A set of math libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/math"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
# dependency due to ArrayTraitExt::concat in ed25519.cairo
alexandria_data_structures = { path = "../data_structures" }

[dev-dependencies]
cairo_test.workspace = true