# This crate is for tests purposes to avoid having tests running twice if we would be running them crate by crate.
[crate_roots]
alexandria_data_structures = "alexandria/data_structures/src"
alexandria_encoding = "alexandria/encoding/src"
alexandria_math = "alexandria/math/src"
alexandria_sorting = "alexandria/sorting/src"
alexandria_searching = "alexandria/searching/src"
