[package]
name = "alexandria_btc"
version.workspace = true
description = "Bitcoin utilities for Cairo - address generation, key management, and more"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/btc"
edition = "2023_11"
cairo-version = "2.12.1"

[tool]
fmt.workspace = true

[dependencies]
alexandria_encoding = { path = "../encoding", version = "0.6.1" }
alexandria_data_structures = { path = "../data_structures", version = "0.6.1" }
alexandria_math = { path = "../math", version = "0.6.1" }
alexandria_bytes = { path = "../bytes", version = "0.6.1" }


[dev-dependencies]
snforge_std.workspace = true