[package]
name = "alexandria_encoding"
version.workspace = true
description = "Encoding utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/encoding"
edition = "2023_11"
cairo-version = "2.12.2"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version ="0.6.1" }
alexandria_numeric = { path = "../numeric", version ="0.6.1" }
alexandria_bytes = { path = "../bytes", version ="0.6.1" }
alexandria_data_structures = { path = "../data_structures", version ="0.6.1" }


[dev-dependencies]
snforge_std.workspace = true