[package]
name = "alexandria_encoding"
version = "0.1.0"
description = "Encoding utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/encoding"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math" }
alexandria_numeric = { path = "../numeric" }
alexandria_bytes = { path = "../bytes" }

[dev-dependencies]
cairo_test.workspace = true