[package]
name = "alexandria_linalg"
version.workspace = true
description = "A set of linear algebra libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/linalg"
edition = "2023_11"
cairo-version = "2.15.0"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version ="0.8.0" }

[dev-dependencies]
snforge_std.workspace = true
