[package]
name = "alexandria_linalg"
version = "0.1.0"
description = "A set of linear algebra libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/linalg"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math" }
