[package]
name = "alexandria_merkle_tree"
version.workspace = true
description = "Merkle tree related stuff"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/merkle_tree"
edition = "2023_11"
cairo-version = "2.14.0"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version = "0.7.0" }

[dev-dependencies]
snforge_std.workspace = true
