[package]
name = "alexandria_sorting"
version = "0.1.0"
description = "A set of sorting algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/sorting"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
alexandria_data_structures = { path = "../data_structures" }

[dev-dependencies]
cairo_test.workspace = true