[package]
name = "alexandria_sorting"
version.workspace = true
description = "A set of sorting algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/sorting"
edition = "2023_11"
cairo-version = "2.14.0"

[tool]
fmt.workspace = true

[dependencies]
alexandria_data_structures = { path = "../data_structures", version = "0.8.0" }

[dev-dependencies]
snforge_std.workspace = true
