[package]
name = "alexandria_storage"
version = "0.3.0"
description = "Starknet storage utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/src/storage"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
snforge_std.workspace = true
starknet.workspace = true
