[package]
name = "alexandria_storage"
version = "0.3.0"
description = "Starknet storage utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/src/storage"

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
