[package]
name = "alexandria_storage"
version = "0.2.0"
description = "Starknet storage utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/src/storage"

[dependencies]
starknet.workspace = true
