[package]
name = "macros_tests"
description = "Dummy package only used to test macros. Not part of the workspace."
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.15.0"

[dependencies]
starknet = "2.15.0"
alexandria_macros = { path = "../macros", version = "*" }
alexandria_math = { path = "../math", version = "*" }

[dev-dependencies]
snforge_std.workspace = true
