[package]
name = "alexandria_utils"
version.workspace = true
description = "Cairo utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/utils"
edition = "2023_11"
cairo-version = "2.11.2"

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true