[package]
name = "alexandria_ascii"
version.workspace = true
description = "utilities for working with ascii values"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/ascii"
edition = "2023_11"
cairo-version = "2.11.2"

[tool]
fmt.workspace = true

[dependencies]
alexandria_data_structures = { path = "../data_structures", version ="0.5.1" }

[dev-dependencies]
cairo_test.workspace = true