[package]
name = "alexandria_bytes"
version.workspace = true
description = "An implementation similar to Solidity bytes written in Cairo 1"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/bytes"
edition = "2023_11"
cairo-version = "2.14.0"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version ="0.8.0" }
alexandria_data_structures = { path = "../data_structures", version ="0.8.0" }

starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
