[package]
name = "alexandria_bytes"
version = "0.1.0"
description = "An implementation similar to Solidity bytes written in Cairo 1"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/bytes"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math" }
alexandria_data_structures = { path = "../data_structures" }
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true
